# config.yaml
device:
  type: GPU
  model: A5000
  count: 1

model:
  name: mixtral:latest
  quantization: Q4_K_M
  calibration: base

evaluation:
  task: translation
  metrics:
    BLEU: true
    METEOR: true
    BERTScore: true
    tps: true
    power_consumption: false
    memory_usage: false
  output_dir: ./results/translation