device:
  type: GPU
  model: A5000
  count: 1

model:
  name: llama3.3:70b 
  quantization: Q4_K_M
  calibration: base

evaluation:
  task: chatbot
  metrics:
    precision: true
    recall: true
    f1: true
    tps: true
    power_consumption: false
    memory_usage: false
  output_dir: ./results/chatbot